# Generated by Django 3.0.2 on 2020-02-05 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0005_competition_tag'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavorate',
            new_name='UserFavorite',
        ),
    ]
