# Generated by Django 3.0.2 on 2020-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200205_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='competition',
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='数据id'),
        ),
    ]
