# Generated by Django 3.0.3 on 2020-02-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20200205_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='rank',
            field=models.CharField(choices=[('uncertain', '未确定'), ('first', '一等奖'), ('second', '二等奖'), ('third', '三等奖')], default='uncertain', max_length=10),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='teacher',
            field=models.IntegerField(default=0, verbose_name='指导教师'),
        ),
    ]
