# Generated by Django 3.0.2 on 2020-02-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20200214_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='leader_stu',
        ),
    ]
