# Generated by Django 3.0.2 on 2020-02-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20200214_1809'),
        ('operation', '0005_remove_userteam_leader_stu'),
    ]

    operations = [
    ]
