# Generated by Django 3.0.2 on 2020-03-01 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0006_merge_20200215_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=50, verbose_name='竞赛名')),
                ('level', models.CharField(choices=[('nation', '国家级'), ('province', '省级'), ('city', '市级'), ('school', '校级'), ('college', '院级')], max_length=10, verbose_name='等級')),
                ('rank', models.CharField(choices=[('uncertain', '未确定'), ('first', '一等奖'), ('second', '二等奖'), ('third', '三等奖')], default='uncertain', max_length=10)),
                ('apply_image', models.ImageField(default='media/image/default.png', upload_to='media/image/%Y/%m', verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
