# Generated by Django 3.0.2 on 2020-03-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_userapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapply',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='是否被认证'),
        ),
    ]
