# Generated by Django 3.0.2 on 2020-01-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default=0, max_length=11, verbose_name='移动电话'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stu_class',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stu_major',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teacher_title',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='职称'),
        ),
    ]
