# Generated by Django 3.0.2 on 2020-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200209_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stu_class',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stu_major',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stu_college_major',
            field=models.CharField(choices=[('rjxyrjgc', '软件学院软件工程'), ('rjxywlgc', '软件学院网络安全'), ('gjxxyrjxy', '国际信息与软件学院'), ('wdzxy', '微电子学院')], default='', max_length=20, verbose_name='学院专业'),
        ),
    ]
