# Generated by Django 3.0.2 on 2020-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200211_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stu_college_major',
            field=models.CharField(blank=True, choices=[('rjxyrjgc', '软件学院软件工程'), ('rjxywlgc', '软件学院网络安全'), ('gjxxyrjxy', '国际信息与软件学院'), ('wdzxy', '微电子学院')], default='rjxyrjgc', max_length=20, null=True, verbose_name='学院专业'),
        ),
    ]
