# Generated by Django 3.0.3 on 2020-02-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200211_1434'),
    ]

    operations = [
    ]
