# Generated by Django 3.0.2 on 2020-02-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200214_1754'),
        ('users', '0012_auto_20200214_1809'),
    ]

    operations = [
    ]
