# Generated by Django 2.2.2 on 2020-04-03 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='竞赛名')),
                ('desc', models.CharField(max_length=300, verbose_name='竞赛描述')),
                ('category', models.CharField(default='科创竞赛', max_length=20, verbose_name='竞赛类别')),
                ('detail', models.TextField(verbose_name='竞赛详情')),
                ('level', models.CharField(choices=[('nation', '国家级'), ('province', '省级'), ('city', '市级'), ('school', '校级'), ('college', '院级')], max_length=10, verbose_name='等級')),
                ('tag', models.CharField(default='', max_length=20, verbose_name='课程标签')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('students', models.IntegerField(default=0, verbose_name='参加人数')),
                ('admitted_students', models.IntegerField(default=4, verbose_name='队伍最多人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '竞赛',
                'verbose_name_plural': '竞赛',
            },
        ),
        migrations.CreateModel(
            name='CompetitionResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('download', models.FileField(upload_to='media/competitions/resource/%Y/%m', verbose_name='文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition', verbose_name='竞赛')),
            ],
            options={
                'verbose_name': '竞赛资源',
                'verbose_name_plural': '竞赛资源',
            },
        ),
    ]
