# Generated by Django 3.0.2 on 2020-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[('nation', '国家级'), ('province', '省级'), ('city', '市级'), ('school', '校级'), ('college', '院级')], max_length=10, verbose_name='等級'),
        ),
    ]
