# Generated by Django 3.0.2 on 2020-02-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20200121_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='image',
        ),
    ]
