# Generated by Django 3.0.2 on 2020-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_remove_competition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='category',
            field=models.CharField(default='科创竞赛', max_length=20, verbose_name='课程类别'),
        ),
    ]
