# Generated by Django 3.0.2 on 2020-02-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competition_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
