# Generated by Django 3.0.2 on 2020-03-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='admitted_students',
            field=models.IntegerField(default=4, verbose_name='队伍最多人数'),
        ),
    ]
