# Generated by Django 3.0.2 on 2020-03-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competition_admitted_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='category',
            field=models.CharField(default='科创竞赛', max_length=20, verbose_name='竞赛类别'),
        ),
    ]
